### ISSUE TITLE
Upload the site to AWS

### ISSUE THREAD

**Issue by powellsl99** [david-fisher/320-S20-Track1#97]

**Comment by dergoose** [comment]
Links courtesy of Alissa:

https://stackoverflow.com/questions/51218979/react-router-doesnt-work-in-aws-s3-bucket

https://hackernoon.com/hosting-static-react-websites-on-aws-s3-cloudfront-with-ssl-924e5c134455

Changed cloudfront origin URL to the hosting URL found under "static web hosting" within the amazon s3 bucket, as well as set the error page under static web hosting in the S3 bucket "donutmonkeybucket3" to index.html.
